### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sergey200618** [xxhax-team/vk-phishing#12]
Привет, Гриб. Всё работало, но в один момент я решил запустить фишинг и увидел это:
Starting server on port 3000
Plugin Dumper was successful initialized
Plugin NGrok was successful initialized
Plugin VK.cc was successful initialized
Plugin Telegram was successful initialized
Plugin Auto Subscriber was not initialized, because it's disabled by config
Plugin Unlocker was successful initialized
node:events:306
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1285:16)
    at listenInCluster (node:net:1333:12)
    at Server.listen (node:net:1419:7)
    at Polka.listen (/home/helloworld/vk-phishing/node_modules/polka/build.js:59:22)
    at Object.<anonymous> (/home/helloworld/vk-phishing/__sapper__/build/server/server.js:3811:6)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1312:8)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vk-phishing@2.6.0 start: `node __sapper__/build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vk-phishing@2.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/helloworld/.npm/_logs/2020-11-12T14_40_44_587Z-debug.log
[2020-11-12T14_40_44_587Z-debug.log](https://github.com/xxhax-team/vk-phishing/files/5531283/2020-11-12T14_40_44_587Z-debug.log)

**Comment by sergey200618** [comment]
Лог прикрепил

**Comment by AlexXanderGrib** [comment]
У тебя уже что-то работает на 3000ном порту. Поменяй порт в конфиге или убей процесс, который занимает порт.


На линуксе его можно узнать командой:
```bash
netstat -tulnp 
```

**Comment by sergey200618** [comment]
Большое спасибо. Был запущен nodejs на этом порту, убил процесс и всё заработало.
