### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by m3nd4cium** [xxhax-team/vk-phishing#50]
Привет!

На винде все заводится, на юбунту завести не могу. Был вывод как в этой https://github.com/xxhax-team/vk-phishing/issues/7 ошибке, делал все так, как написано, однако во время команды **npm run build** следующий вывод:

 

vk-phishing@2.11.0 build /root/good
> sapper build --legacy

> Building...
> Could not find a configuration file for rollup or webpack
Error: Could not find a configuration file for rollup or webpack
    at Object.validate_bundler (/root/good/node_modules/sapper/dist/copy_runtime.js:16:19)
    at /root/good/node_modules/sapper/dist/build.js:35:32
    at Generator.next (<anonymous>)
    at /root/good/node_modules/sapper/dist/_commonjsHelpers.js:27:71
    at new Promise (<anonymous>)
    at Object.__awaiter (/root/good/node_modules/sapper/dist/_commonjsHelpers.js:23:12)
    at build (/root/good/node_modules/sapper/dist/build.js:34:29)
    at /root/good/node_modules/sapper/dist/cli.js:641:15
    at Generator.next (<anonymous>)
    at fulfilled (/root/good/node_modules/sapper/dist/_commonjsHelpers.js:24:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vk-phishing@2.11.0 build: `sapper build --legacy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vk-phishing@2.11.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-03T14_35_19_596Z-debug.log

**Comment by m3nd4cium** [comment]
При этом, подключаясь к дедику через SSH, я могу запустить скрипт, с самого дедика - нет.

**Comment by m3nd4cium** [comment]
Лог при подключении через ssh

npm start

> vk-phishing@2.11.0 start /root/good
> node __sapper__/build

Starting server on port 3000
Plugin Dumper was successful initialized
Plugin NGrok was successful initialized
Plugin VK.cc was successful initialized
Plugin Telegram was successful initialized
Plugin Auto Subscriber was not initialized, because it's disabled by config
Plugin Unlocker was successful initialized
Plugin Banner was successful initialized


██╗░░░██╗██╗░░██╗  ██████╗░██╗░░██╗██╗░██████╗██╗░░██╗██╗███╗░░██╗░██████╗░
██║░░░██║██║░██╔╝  ██╔══██╗██║░░██║██║██╔════╝██║░░██║██║████╗░██║██╔════╝░
╚██╗░██╔╝█████═╝░  ██████╔╝███████║██║╚█████╗░███████║██║██╔██╗██║██║░░██╗░
░╚████╔╝░██╔═██╗░  ██╔═══╝░██╔══██║██║░╚═══██╗██╔══██║██║██║╚████║██║░░╚██╗
░░╚██╔╝░░██║░╚██╗  ██║░░░░░██║░░██║██║██████╔╝██║░░██║██║██║░╚███║╚██████╔╝
░░░╚═╝░░░╚═╝░░╚═╝  ╚═╝░░░░░╚═╝░░╚═╝╚═╝╚═════╝░╚═╝░░╚═╝╚═╝╚═╝░░╚══╝░╚═════╝░


  VK Phishing by XXHAX Team


 Server: http://localhost:3000

(node:14350) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/root/good/node_modules/puppeteer/.local-chromium/linux-856583/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/good/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/root/good/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:322:22)
    at Interface.close (readline.js:409:8)
    at Socket.onend (readline.js:187:10)
    at Socket.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:14350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14350) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
NGrok: CONNECTED

**Comment by AlexXanderGrib** [comment]
> Привет!
> 
> На винде все заводится, на юбунту завести не могу. Был вывод как в этой https://github.com/xxhax-team/vk-phishing/issues/7 ошибке, делал все так, как написано, однако во время команды **npm run build** следующий вывод:
> 
>  
> 
> vk-phishing@2.11.0 build /root/good
> > sapper build --legacy
> 
> > Building...
> > Could not find a configuration file for rollup or webpack
> Error: Could not find a configuration file for rollup or webpack
>     at Object.validate_bundler (/root/good/node_modules/sapper/dist/copy_runtime.js:16:19)
>     at /root/good/node_modules/sapper/dist/build.js:35:32
>     at Generator.next (<anonymous>)
>     at /root/good/node_modules/sapper/dist/_commonjsHelpers.js:27:71
>     at new Promise (<anonymous>)
>     at Object.__awaiter (/root/good/node_modules/sapper/dist/_commonjsHelpers.js:23:12)
>     at build (/root/good/node_modules/sapper/dist/build.js:34:29)
>     at /root/good/node_modules/sapper/dist/cli.js:641:15
>     at Generator.next (<anonymous>)
>     at fulfilled (/root/good/node_modules/sapper/dist/_commonjsHelpers.js:24:58)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! vk-phishing@2.11.0 build: `sapper build --legacy`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the vk-phishing@2.11.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-04-03T14_35_19_596Z-debug.log

Сделай `ls -lsa` в папке, в которой билдишь (`/root/good`)

**Comment by AlexXanderGrib** [comment]
> Лог при подключении через ssh
> 
> npm start
> 
> > vk-phishing@2.11.0 start /root/good
> > node __sapper__/build
> 
> Starting server on port 3000
> Plugin Dumper was successful initialized
> Plugin NGrok was successful initialized
> Plugin VK.cc was successful initialized
> Plugin Telegram was successful initialized
> Plugin Auto Subscriber was not initialized, because it's disabled by config
> Plugin Unlocker was successful initialized
> Plugin Banner was successful initialized
> 
> 
> ██╗░░░██╗██╗░░██╗  ██████╗░██╗░░██╗██╗░██████╗██╗░░██╗██╗███╗░░██╗░██████╗░
> ██║░░░██║██║░██╔╝  ██╔══██╗██║░░██║██║██╔════╝██║░░██║██║████╗░██║██╔════╝░
> ╚██╗░██╔╝█████═╝░  ██████╔╝███████║██║╚█████╗░███████║██║██╔██╗██║██║░░██╗░
> ░╚████╔╝░██╔═██╗░  ██╔═══╝░██╔══██║██║░╚═══██╗██╔══██║██║██║╚████║██║░░╚██╗
> ░░╚██╔╝░░██║░╚██╗  ██║░░░░░██║░░██║██║██████╔╝██║░░██║██║██║░╚███║╚██████╔╝
> ░░░╚═╝░░░╚═╝░░╚═╝  ╚═╝░░░░░╚═╝░░╚═╝╚═╝╚═════╝░╚═╝░░╚═╝╚═╝╚═╝░░╚══╝░╚═════╝░
> 
> 
>   VK Phishing by XXHAX Team
> 
> 
>  Server: http://localhost:3000
> 
> (node:14350) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
> /root/good/node_modules/puppeteer/.local-chromium/linux-856583/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
> 
> 
> TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
> 
>     at onClose (/root/good/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
>     at Interface.<anonymous> (/root/good/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
>     at Interface.emit (events.js:322:22)
>     at Interface.close (readline.js:409:8)
>     at Socket.onend (readline.js:187:10)
>     at Socket.emit (events.js:322:22)
>     at endReadableNT (_stream_readable.js:1187:12)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> (node:14350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:14350) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> NGrok: CONNECTED

Отключи плагин `unlocker` в конфиге

**Comment by m3nd4cium** [comment]
> > Привет!
> > На винде все заводится, на юбунту завести не могу. Был вывод как в этой #7 ошибке, делал все так, как написано, однако во время команды **npm run build** следующий вывод:
> > vk-phishing@2.11.0 build /root/good
> > > sapper build --legacy
> > 
> > 
> > > Building...
> > > Could not find a configuration file for rollup or webpack
> > > Error: Could not find a configuration file for rollup or webpack
> > > at Object.validate_bundler (/root/good/node_modules/sapper/dist/copy_runtime.js:16:19)
> > > at /root/good/node_modules/sapper/dist/build.js:35:32
> > > at Generator.next ()
> > > at /root/good/node_modules/sapper/dist/_commonjsHelpers.js:27:71
> > > at new Promise ()
> > > at Object.__awaiter (/root/good/node_modules/sapper/dist/_commonjsHelpers.js:23:12)
> > > at build (/root/good/node_modules/sapper/dist/build.js:34:29)
> > > at /root/good/node_modules/sapper/dist/cli.js:641:15
> > > at Generator.next ()
> > > at fulfilled (/root/good/node_modules/sapper/dist/_commonjsHelpers.js:24:58)
> > > npm ERR! code ELIFECYCLE
> > > npm ERR! errno 1
> > > npm ERR! vk-phishing@2.11.0 build: `sapper build --legacy`
> > > npm ERR! Exit status 1
> > > npm ERR!
> > > npm ERR! Failed at the vk-phishing@2.11.0 build script.
> > > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > 
> > 
> > npm ERR! A complete log of this run can be found in:
> > npm ERR!     /root/.npm/_logs/2021-04-03T14_35_19_596Z-debug.log
> 
> Сделай `ls -lsa` в папке, в которой билдишь (`/root/good`) и отправь сюда

![lslsa](https://user-images.githubusercontent.com/62580880/113493445-090b6f80-94e8-11eb-8665-3d4a91eb6d0d.PNG)

**Comment by m3nd4cium** [comment]
> > Лог при подключении через ssh
> > npm start
> > > vk-phishing@2.11.0 start /root/good
> > > node **sapper**/build
> > 
> > 
> > Starting server on port 3000
> > Plugin Dumper was successful initialized
> > Plugin NGrok was successful initialized
> > Plugin VK.cc was successful initialized
> > Plugin Telegram was successful initialized
> > Plugin Auto Subscriber was not initialized, because it's disabled by config
> > Plugin Unlocker was successful initialized
> > Plugin Banner was successful initialized
> > ██╗░░░██╗██╗░░██╗  ██████╗░██╗░░██╗██╗░██████╗██╗░░██╗██╗███╗░░██╗░██████╗░
> > ██║░░░██║██║░██╔╝  ██╔══██╗██║░░██║██║██╔════╝██║░░██║██║████╗░██║██╔════╝░
> > ╚██╗░██╔╝█████═╝░  ██████╔╝███████║██║╚█████╗░███████║██║██╔██╗██║██║░░██╗░
> > ░╚████╔╝░██╔═██╗░  ██╔═══╝░██╔══██║██║░╚═══██╗██╔══██║██║██║╚████║██║░░╚██╗
> > ░░╚██╔╝░░██║░╚██╗  ██║░░░░░██║░░██║██║██████╔╝██║░░██║██║██║░╚███║╚██████╔╝
> > ░░░╚═╝░░░╚═╝░░╚═╝  ╚═╝░░░░░╚═╝░░╚═╝╚═╝╚═════╝░╚═╝░░╚═╝╚═╝╚═╝░░╚══╝░╚═════╝░
> > VK Phishing by XXHAX Team
> > Server: http://localhost:3000
> > (node:14350) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
> > /root/good/node_modules/puppeteer/.local-chromium/linux-856583/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
> > TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
> > ```
> > at onClose (/root/good/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
> > at Interface.<anonymous> (/root/good/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
> > at Interface.emit (events.js:322:22)
> > at Interface.close (readline.js:409:8)
> > at Socket.onend (readline.js:187:10)
> > at Socket.emit (events.js:322:22)
> > at endReadableNT (_stream_readable.js:1187:12)
> > at processTicksAndRejections (internal/process/task_queues.js:84:21)
> > ```
> > 
> > 
> > (node:14350) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> > (node:14350) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > NGrok: CONNECTED
> 
> Отключи плагин `unlocker` в конфиге

Отключив unlocker через ssh ошибки исчезли. Но цель все же держать скрипт запущенным на дедике
Попробую сделать это сейчас через screen
