### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Strannik74** [xxhax-team/vk-phishing#7]
npm start

> vk-phishing@2.0.0 start /root/PHISHING/vk-phishing
> node __sapper__/build

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/PHISHING/vk-phishing/__sapper__/build'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vk-phishing@2.0.0 start: `node __sapper__/build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vk-phishing@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-13T12_55_57_701Z-debug.log

**Comment by AlexXanderGrib** [comment]
Try this command in terminal
```bash
npm run build
```

**Comment by Strannik74** [comment]
Kali Linux
Compiled node-12
npm install
npm run build
npm audit fix
npm start
