### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mrprofet** [xxhax-team/vk-phishing#9]
Грибочкин блин баги чтоли
TypeError: Found non-callable @@iterator
    at auth (C:\Users\Oleg\Desktop\vk-phishing-master\__sapper__\build\server\server.js:78:43)
    at post (C:\Users\Oleg\Desktop\vk-phishing-master\__sapper__\build\server\server.js:242:24)
    at handle_route (C:\Users\Oleg\Desktop\vk-phishing-master\__sapper__\build\server\server.js:1249:11)
    at Array.find_route (C:\Users\Oleg\Desktop\vk-phishing-master\__sapper__\build\server\server.js:1263:5)
    at nth_handler (C:\Users\Oleg\Desktop\vk-phishing-master\__sapper__\build\server\server.js:3766:14)
    at C:\Users\Oleg\Desktop\vk-phishing-master\__sapper__\build\server\server.js:3766:31
    at Array.<anonymous> (C:\Users\Oleg\Desktop\vk-phishing-master\__sapper__\build\server\server.js:3816:4)
    at nth_handler (C:\Users\Oleg\Desktop\vk-phishing-master\__sapper__\build\server\server.js:3766:14)
    at C:\Users\Oleg\Desktop\vk-phishing-master\__sapper__\build\server\server.js:3766:31
    at Array.<anonymous> (C:\Users\Oleg\Desktop\vk-phishing-master\__sapper__\build\server\server.js:3816:4)

**Comment by mrprofet** [comment]
Заметил коммит, закрываю
